class LocationError(Exception):
    pass

class CallBackError(Exception):
    pass